firstaid 기초작업
mindscale/firstaid pull request #1
Opened 2018-03-28 05:21 UTC by yirey

네 가지 자료 유형을 다룰 수 있습니다
- 글씨
- 이미지
- 표
- 차트

![screen shot 2018-03-28 at 2 19 06 pm](https://user-images.githubusercontent.com/22827917/38010250-297c88a4-3293-11e8-9aad-8bddc320b3f6.png)
![screen shot 2018-03-28 at 2 18 48 pm](https://user-images.githubusercontent.com/22827917/38010252-29b97e1c-3293-11e8-9cbf-da4ff0d858fd.png)
![screen shot 2018-03-28 at 2 18 34 pm](https://user-images.githubusercontent.com/22827917/38010253-29e2d154-3293-11e8-96c0-3b97d6372767.png)
![screen shot 2018-03-28 at 2 18 25 pm](https://user-images.githubusercontent.com/22827917/38010254-2a0ae25c-3293-11e8-9310-f8fb602262a0.png)
![screen shot 2018-03-28 at 2 18 15 pm](https://user-images.githubusercontent.com/22827917/38010255-2a32bc82-3293-11e8-8801-2dc22cd190e1.png)
![screen shot 2018-03-28 at 2 19 28 pm](https://user-images.githubusercontent.com/22827917/38010256-2bc195a0-3293-11e8-96c9-a3ad07e12760.png)
![screen shot 2018-03-28 at 2 19 17 pm](https://user-images.githubusercontent.com/22827917/38010257-2bea2862-3293-11e8-8fdb-ca84ed745308.png)

2018-03-28 08:07 UTC, yirey commented on firstaid/pptx.py
> +            if reverse:  # horizontal placeholder
`if lim_width > lim_height: `  --> 으로 바꾸고 reverse 빼기

2018-03-28 09:04 UTC, positive-song approved these changes

2018-03-29 03:16 UTC, euphoris requested changes

2018-03-29 03:16 UTC, euphoris commented on firstaid/pptx.py
> +            print('지원하지 않는 자료입니다')
`raise TypeError`로 바꾸는 게 좋을 듯

2018-03-29 06:45 UTC, yirey commented
수정해서 푸시했습니다~

2018-04-02 01:29 UTC, euphoris approved these changes

2018-04-02 01:29 UTC, merged